{{- if .Values.secrets.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "podwatch.fullname" . }}-secret
type: Opaque
data:

  PODWATCH_CLIENT_SECRET: {{ .Values.secrets.clientSecret | b64enc }}
{{- end }}