{{- if .Values.secrets.PODWATCH_CLIENT_SECRET }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "podwatch.fullname" . }}-secret
type: Opaque
data:

  PODWATCH_CLIENT_SECRET: {{ .Values.secrets.PODWATCH_CLIENT_SECRET }}
{{- end }}